# codecov.yml
coverage:
    status:
        project:
            default:
                target: 70%
        patch:
            default:
                target: 80%
                threshold: 1%

comment:
    layout: "reach, diff, flags"
