# codecov.yml
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 92%
        threshold: 2%

comment:
  layout: "reach, diff, flags"
