name: Good First Issue Template
description: Create a Good First Issue for new contributors
title: "[Good First Issue]: "
labels: ["Good First Issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        ## **Thanks for creating a good first issue!** 😊

        We truly appreciate your time and effort, welcome!.
        This template is designed to help you create a Good First Issue (GFI) : a small, well-scoped task that helps new contributors learn the codebase and workflow.
        ---
  - type: textarea
    id: intro
    attributes:
      label: 🆕🐥 Newcomer Friendly
      description: Who is this issue for?
      value: |
        Welcome 👋  

        This **Good First Issue** is a beginner-friendly starting point for the Hiero Python SDK.

        You don’t need any background in:
        - Hiero or Hedera
        - distributed ledger technology

        If you’re comfortable with **basic Python** and **Git**, you’re ready to get started.

  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > #### 📋 Good First Issue (GFI) Guidelines
        > A **Good First Issue [Guidelines](docs/maintainers/good_first_issue_candidate_guidelines.md)** is a small, well-scoped task that helps new contributors get familiar with the codebase and contribution workflow.
        >
        > **Often a good fit for Good First Issues:**
        > - Spelling or grammar fixes
        > - Small documentation formatting improvements
        > - Purely structural refactors of examples
        > - Minor, clearly described edits to docstrings or comments
        > - Light file moves or renames for clarity
        > - Applying formatting tools (e.g. `black`, `ruff`) in limited areas
        >
        > More involved tasks may be a better fit for **Beginner**, **Intermediate**, or **Advanced** issues.
        >
        > If you’re unsure, the **Good First Issue Candidate Template** can be used.

  - type: textarea
    id: issue
    attributes:
      label: 👾 Issue description
      description: |
        Describe the issue in a way that’s easy for new contributors to understand.
        Please avoid assuming prior knowledge of the language, codebase, or Hiero, as Good First Issues are often surfaced to new developers.
        Links to relevant documentation or code are very welcome.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for problem (hidden in submission) -->
        ## 👾 Description of the issue - Example

        The example for Token Associate Transaction located at examples/tokens/token_associate_transaction.py can be improved. It correctly illustrates how to associate a token, however, it does so all from one function main()

        As everything is grouped together in main(), it is difficult for a user to understand all the individual steps required to associate a token.

        For example:
        ```python

        def run_demo():
            """Monolithic token association demo."""
            print(f"🚀 Connecting to Hedera {network_name} network!")    
            client = Client(Network(network_name))
            operator_id = AccountId.from_string(os.getenv("OPERATOR_ID", ""))
            operator_key = PrivateKey.from_string(os.getenv("OPERATOR_KEY", ""))
            client.set_operator(operator_id, operator_key)
            print(f"✅ Client ready (operator {operator_id})")

            test_key = PrivateKey.generate_ed25519()
            receipt = (
                AccountCreateTransaction()
                .set_key(test_key.public_key())
                .set_initial_balance(Hbar(1))
                .set_account_memo("Test account for token association demo")
                .freeze_with(client)
                .sign(operator_key)
                .execute(client)
            )
            if receipt.status != ResponseCode.SUCCESS:
                raise Exception(receipt.status)
            account_id = receipt.account_id
            print(f"✅ Created test account {account_id}")

            # Create tokens
            tokens = []
            for i in range(3):
                try:
                    receipt = (
                        TokenCreateTransaction()
                        .set_token_name(f"DemoToken{i}")
                        .set_token_symbol(f"DTK{i}")
                        .set_decimals(2)
                        .set_initial_supply(100_000)
                        .set_treasury_account_id(operator_id)
                        .freeze_with(client)
                        .sign(operator_key)
                        .execute(client)
                    )
                    if receipt.status != ResponseCode.SUCCESS:
                        raise Exception(receipt.status)
                    token_id = receipt.token_id
                    tokens.append(token_id)
                    print(f"✅ Created token {token_id}")
                except Exception as e:
                    print(f"❌ Token creation failed: {e}")
                    sys.exit(1)

            # Associate first token
            try:
                TokenAssociateTransaction().set_account_id(account_id).add_token_id(tokens[0]).freeze_with(client).sign(test_key).execute(client)
                print(f"✅ Token {tokens[0]} associated with account {account_id}")
            except Exception as e:
                print(f"❌ Token association failed: {e}")
                sys.exit(1)
        ```

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: |
        Describe what a good solution would look like.
        Keep this high-level and easy to understand. Implementation details can go in the subsequent Implementation Steps section.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example for the solution (hidden in submission) -->
        ## 💡 Solution - Example

        For the TokenAssociateTransaction example, the solution is to split the monolithic main() function for illustrating TokenAssociateTransaction into separate smaller functions which are called from main().
        Such as:
        - Setting up the client
        - Creating an account
        - Creating a token
        - Associating the account to the token

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation Steps
      description: |
        To make this issue easy to pick up and complete, please include:
        - Which files need to be changed or added
        - Any functions, classes, or modules involved
        - The complete steps to implement the solution
        - What the final result or output should look like
        - Links to relevant documentation or code (if helpful)
        For good first issues, please keep this as guided and clear as possible.
      value: |
        Edit here. Example provided below.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example implementation (hidden in submission) -->
        #### 👩‍💻 Implementation - Example

        To break down the monolithic main function, you need to:
        - [ ] Extract the Key Steps (set up a client, create a test account, create a token, associate the token)
        - [ ] Copy and paste the functionality for each key step into its own function
        - [ ] Pass to each function the variables you need to run it
        - [ ] Call each function in main()
        - [ ] Ensure you return the values you'll need to pass on to the next step in main
        - [ ] Ensure the example still runs and has the same output!

        For example:
        ```python

        def setup_client():
            """Initialize and set up the client with operator account."""

        def create_test_account(client, operator_key):
            """Create a new test account for demonstration."""

        def create_fungible_token(client, operator_id, operator_key):
            """Create a fungible token for association with test account."""

        def associate_token_with_account(client, token_id, account_id, account_key):
            """Associate the token with the test account."""

        def main():
            client, operator_id, operator_key = setup_client()
            account_id, account_private_key = create_test_account(client, operator_key)
            token_id = create_fungible_token(client, operator_id, operator_key)
            associate_token_with_account(client, token_id, account_id, account_private_key)
        ```

  - type: textarea
    id: setup_steps
    attributes:
      label: 📋 Step-by-Step Setup Guide
      description: Provide a step-by-step setup guide for new contributors
      value: |
        #### Suggestions:
        - [ ] Visual Studio (VS) Code: [Guide](docs/sdk_developers/training/workflow/01_supporting_infrastructure.md)

        - [ ] GitHub Desktop: [Guide](docs/sdk_developers/training/workflow/01_supporting_infrastructure.md)

        - [ ] Hedera Testnet Account with root .env file: [Guide](docs/sdk_developers/training/setup/03_setting_up_env.md)

        - [ ] Create a GPG key linked to GitHub: [Guide](docs/sdk_developers/signing.md)

        #### Setup the Hiero Python SDK for development
        - [ ] **Fork** Create an online and local copy of the repository: [Guide](docs/sdk_developers/training/workflow/02_forking_python_sdk.md)

        - [ ] **Connect** origin with upstream: [Guide](docs/sdk_developers/training/workflow/03_staying_in_sync.md)

        - [ ] **Install Packages** Install packages and protobuffs: [Guide](docs/sdk_developers/training/setup/02_installing_hiero_python_sdk.md)

        - [ ] **Sync Main** pull any recent upstream changes: [Guide](docs/sdk_developers/rebasing.md)

        You are set up! 🎉
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Step-by-step contribution guide
      description: Provide a contribution workflow suitable for new contributors.
      value: |
        #### ✅ Get ready
        - [ ] **Claim the issue:**  comment `/assign`: [Guide](docs/sdk_developers/training/workflow/04_assigning_issues.md)

        - [ ] **Double check the Issue and AI plan:** carefully re-read the issue description and the CodeRabbit AI plan

        - [ ] **Ask questions early:** ask on [Discord](docs/discord.md), your `@mentor` (Python SDK help) and the `@good_first_issue_support_team` (setup and workflow help)

        - [ ] **Sync with main:** pull the latest upstream changes [Guide](docs/sdk_developers/rebasing.md)

        #### 🛠️ Solve the Issue
        - [ ] **Create a branch from `main`:** [Guide](docs/sdk_developers/training/workflow/05_working_branches.md)

        - [ ] **Implement the solution**: follow the implementation steps in the issue description.

        - [ ] **Commit with DCO and GPG signing:**  commit changes using: `git commit -S -s -m "chore: your message"`, [Guide](docs/sdk_developers/signing.md)

        - [ ] **Add a `.CHANGELOG.md` entry:** under the appropriate **[UNRELEASED]** section and commit as `git commit -S -s -m "chore: changelog entry"` [Guide](docs/sdk_developers/changelog_entry.md)

        #### 🚀 Create the pull request
        - [ ] **Push your commits:**  push your branch to your fork `git push origin your-branch-name`

        - [ ] **Open a pull request:** [here](https://github.com/hiero-ledger/hiero-sdk-python/pulls) [guide](docs/sdk_developers/training/workflow/11_submit_pull_request.md)

        - [ ] **Complete the PR description:**  briefly describe your changes and link the issue, [Guide](docs/sdk_developers/training/workflow/11_submit_pull_request.md)

        - [ ] **Submit the pull request:**  click `**Create pull request**` 🎉

    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance criteria
      description: |
        Edit or expand this checklist with what is required to merge a pull request for this issue.
      value: |
        To be able to close this issue, the following criteria must be met:

        - [ ] **The issue is solved:**  I’ve carefully read and implemented the issue requirements

        - [ ] **I did not add extra changes:**  I did not modify anything beyond what is described in the issue

        - [ ] **Behavior:**  All other existing features continue to work as before

        - [ ] **Checks and feedback:**  All checks pass and any requested changes have been made
    validations:
      required: true

  - type: textarea
    id: pr_expectations
    attributes:
      label: 🤔 What to expect after submitting a PR
      description: Explain what happens after a pull request is opened.
      value: |
        Once you open a pull request, here’s what happens next:

        #### 🤖 Automated checks
        A few automated checks will run and **all must pass** before your PR can be merged, such as:
        - signing 
        - changelog entry
        - solo unit and integration tests
        - examples
        - code quality checks

        👉 You can open each check to see detailed results and error messages if anything fails.


        #### 🤝 AI feedback (CodeRabbit)
        You’ll receive quick feedback from **CodeRabbit AI**, which may:
        - point out potential issues
        - suggest improvements or alternatives

        AI feedback is **advisory** — it can make mistakes - use what’s helpful and feel free to ask questions.


        #### 👀 Maintainer review
        A Python SDK team member will review your PR, typically within **1–3 days**.
        - You may be asked to make changes, or
        - Your PR may be approved as-is ✅

        Once approved, PRs are usually merged within **one day**.

        #### 🔄 Merge conflicts
        Merge conflicts can occasionally happen as the SDK updates. This is normal and fixable.

        - **Changelog conflicts**  
          These are common and can usually be resolved by accepting both changes using GitHub’s online editor in the pull request.

        - **Other conflicts**  
          More complex conflicts may require rebasing your branch and resolving them locally.  
          👉 Follow the step-by-step **[Rebasing Guide](docs/sdk_developers/rebasing.md)** for help.
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: 🤔 Additional Help
      description: Provide any extra resources or context for contributors to solve this good first issue
      value: |
        #### First Points of Contact:
        - [Discord](docs/discord.md)
        - Comment with `@mentor_name` (for Python SDK questions)
        - Comment with `@hiero-ledger/hiero-sdk-good-first-issue-support` (for setup and workflow questions)
        The more you ask, the more you learn and so do we!

        #### Documentation:
        - [README.md](./README.md)
        - [CONTRIBUTING.md](./CONTRIBUTING.md)
        - [Project Structure](docs/sdk_developers/training/setup/project_structure.md)
        - [DCO and Verified Signing Guide](docs/sdk_developers/signing.md)
        - [Changelog Guide](docs/sdk_developers/changelog_entry.md)
        - [Merge Conflicts Guide](docs/sdk_developers/merge_conflicts.md)
        - [Linking Issues Guide](docs/sdk_developers/how_to_link_issues.md)
        - [Rebasing Guide](docs/sdk_developers/rebasing.md)
        - [Workflow Guide](docs/sdk_developers/workflow.md)

        - [Pin Github Actions Guide](docs/sdk_developers/how-to-pin-github-actions.md)
        - [Running Examples](docs/sdk_developers/examples.md)
        - [Testing on Forks](docs/sdk_developers/training/testing_forks.md)

        - [General Training](docs/sdk_developers/training)
        - [General SDK Developer Docs](docs/sdk_developers)

        #### Calls:
        - Get hands-on-help by our expert team at our [Office Hours](https://zoom-lfx.platform.linuxfoundation.org/meeting/99912667426?password=5b584a0e-1ed7-49d3-b2fc-dc5ddc888338)
        - Learn, raise issues and provide feedback at [Community Calls](https://zoom-lfx.platform.linuxfoundation.org/meeting/92041330205?password=2f345bee-0c14-4dd5-9883-06fbc9c60581)

  - type: textarea
    id: ai_usage_guidelines
    attributes:
      label: 🤖 AI usage guidelines
      description: Guidance on using AI tools responsibly for this issue.
      value: |
        You’re welcome to use AI tools while working on this issue.

        **Use AI responsibly:**
        - Verify suggestions before applying them, such as by looking at similar examples
        - Work one small change at a time
        - Create small tests/checks as you go

        **For Hiero Python SDK expert guidance:**
        - Ask a mentor/maintainer, they are happy to guide you on our best practices
