name: Beginner Issue Template
description: Create a beginner issue for contributors ready to work more independently
title: "[Beginner]: "
labels: ["beginner"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        **For issue creators:** Beginner issues sit between Good First Issues and Intermediate issues.
        The contributor should need to read some code, look something up, or make a small decision —
        but not design a solution from scratch.

        If the task can be completed by copy-pasting instructions, it belongs in a Good First Issue.
        If it requires understanding multiple interacting systems, it belongs in Intermediate.

        For detailed guidance, see the
        [Beginner Issue Guidelines](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/maintainers/beginner_issues_guidelines.md).

        **All links in this template must be absolute URLs** (starting with `https://`).
        Relative links break when rendered in GitHub issues.

        ---

  - type: textarea
    id: before_you_start
    attributes:
      label: 🐥 Beginner Friendly
      description: |
        THIS SECTION IS PRE-FILLED. LEAVE AS-IS UNLESS YOU NEED TO ADD ISSUE-SPECIFIC PREREQUISITES.
      value: |
        Welcome! This Beginner Issue is designed to be a natural next step after good first issues.

        It nudges you to:

        - Research existing patterns
        - Own more implementation decisions
        - Test your changes

        **Difficulty:**

        - Requires knowledge of our workflow
        - Beginner to intermediate Python and Git
        - Beginner DLT/Blockchain experience

        > [!IMPORTANT]
        > We recommend completing at least 3 good first issues before attempting a beginner issue.

        > [!TIP]
        > **You should be comfortable with:**
        > - Forking, branching, committing (with DCO + GPG signing), and opening a pull request without a tutorial
        > - Reading beginner Python code you did not write and following its patterns
        > - Handling simple merge conflicts in CHANGELOG.md
        > - Keeping your fork up to date with main by [rebasing](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/rebasing.md)
        > - Looking things up on your own before asking for help

        If any of that feels unfamiliar, good first issues might still be the most rewarding path
        for you right now —
        [find one here](https://github.com/hiero-ledger/hiero-sdk-python/issues?q=is%3Aissue+state%3Aopen+label%3A%22Good+First+Issue%22+no%3Aassignee).
        You can always come back when you are ready.

        **Support:** A maintainer actively monitors this issue and will help guide your implementation ideas.

        ⏱️ Typical time to complete: 4-6 hours
        🧩 Difficulty: Manageable but requires investigation and testing
        🎓 Best for: Beginner contributors

        ---

        🏁 **When this issue is complete, you will have:**

        ✅ Improved your research abilities
        ✅ Improved your knowledge of the codebase
        ✅ Owned implementation decisions
        ✅ Created basic tests
    validations:
      required: false

  - type: textarea
    id: task
    attributes:
      label: 👾 Description of the issue
      description: |
        DESCRIBE WHAT NEEDS TO CHANGE AND WHY.
        INCLUDE WHICH FILE(S) TO LOOK AT, WHAT THE CURRENT BEHAVIOR IS, AND WHAT THE DESIRED BEHAVIOR IS.
        DO NOT WRITE A STEP-BY-STEP RECIPE. POINT THEM TOWARD THE RIGHT AREA AND LET THEM FIGURE OUT THE APPROACH.
        IF A COPY-PASTE RECIPE WOULD SUFFICE, THIS IS A GOOD FIRST ISSUE, NOT A BEGINNER ISSUE.
        PROVIDE ENOUGH CONTEXT SO THE CONTRIBUTOR CAN JUDGE WHETHER THEY ARE READY FOR THIS ISSUE.
        CONSIDER ADDING: EXPECTED TIME (e.g. 2-4 HOURS), RELEVANT LABELS, AND A NOTE TO CHECK THE CODERABBIT AI PLAN.
      value: |
        _Replace this with the task description._

        **Before claiming:**
        - Check the issue labels to see what area this touches
        - Read the CodeRabbit AI plan (posted as a comment) for a rough implementation overview
        - If this feels like too big a step, that is fine — try another beginner issue or a Good First Issue first
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example task (hidden in submission) -->
        ## Example — Description of the issue

        The `AccountId` class in `src/hiero_sdk_python/account/account_id.py` has a `__str__()` method,
        but its `__repr__()` still uses the default object representation:

        ```python
        >>> repr(account_id)
        '<hiero_sdk_python.account.account_id.AccountId object at 0x7f9c2a3b8d60>'
        ```

        That is not useful when debugging. We want `repr()` to show the actual values:

        ```python
        >>> repr(account_id)
        'AccountId(shard=0, realm=0, num=1234)'
        ```

        The class is initialized with `shard`, `realm`, `num`, and an optional `alias_key`.
        Look at how other ID classes in the SDK handle `__repr__()` for the expected pattern.

  - type: textarea
    id: solution
    attributes:
      label: 💡 Solution
      description: |
        BRIEFLY STATE WHAT THE CONTRIBUTOR SHOULD BUILD OR FIX.
        THIS SHOULD BE A SHORT SUMMARY OF THE EXPECTED OUTCOME — NOT A DETAILED IMPLEMENTATION GUIDE.
        EXAMPLE: "Add a __repr__ method to AccountId that shows shard, realm, and num."
      value: |
        _Replace this with a brief solution summary._
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example solution (hidden in submission) -->
        ## Example — Solution

        Add a `__repr__()` method to `AccountId` that returns a string like
        `AccountId(shard=0, realm=0, num=1234)`, including `alias_key` when set.

  - type: textarea
    id: research
    attributes:
      label: 🔍 Background Research
      description: |
        POINT THE CONTRIBUTOR TOWARD RELEVANT FILES, SIMILAR CODE, PYTHON DOCS, OR PATTERNS TO STUDY.
        THIS IS THE "INVESTIGATE BEFORE YOU CODE" STEP.
        THINK: WHAT WOULD A COLLEAGUE TELL YOU IF YOU ASKED "WHERE DO I START?"
        INCLUDE LINKS TO PYTHON DOCUMENTATION IF THE TASK INVOLVES A LANGUAGE CONCEPT.
      value: |
        _Replace this with research pointers._
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example research pointers (hidden in submission) -->
        ## Example — Background Research

        - Open `src/hiero_sdk_python/account/account_id.py` and read the `__init__` and `__str__` methods
        - Look at how `TopicId` and `ContractId` implement `__repr__()` — use the same pattern
        - Python docs on `__repr__`: https://docs.python.org/3/reference/datamodel.html#object.__repr__
        - Ask yourself: what information would help you identify this object during debugging?

  - type: textarea
    id: implementation
    attributes:
      label: 🛠️ Implementation
      description: |
        DESCRIBE WHAT THE CONTRIBUTOR SHOULD BUILD AFTER COMPLETING THEIR RESEARCH.
        KEEP IT HIGH-LEVEL — THEY SHOULD FIGURE OUT THE DETAILS FROM THEIR RESEARCH.
      value: |
        _Replace this with implementation guidance._
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example implementation (hidden in submission) -->
        ## Example — Implementation

        - Implement `__repr__()` on `AccountId` following the pattern you found in similar classes
        - Include `alias_key` in the output when the account uses an alias
        - Add a test to the existing `AccountId` unit test file

  - type: textarea
    id: testing
    attributes:
      label: 🧪 Testing your changes
      description: |
        EDIT THIS SECTION TO MATCH THE TYPE OF CHANGE. DELETE CATEGORIES THAT DO NOT APPLY.
      value: |
        How you test depends on the type of change.
        See the [testing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/testing.md) for full details.

        **Source code changes (e.g. Python files in `src/`):**
        - Write unit tests and run them locally: `uv run pytest tests/unit/<specific_file>_test.py -v`
        - Integration tests will run automatically when you push to your fork or open a PR

        **Example script changes (e.g. files in `examples/`):**
        - Run the example script to confirm it works: instructions are at the top of each script
        - You will need a [Hedera Portal](https://portal.hedera.com/) account for testnet credentials — see [environment setup](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/setup/environment_setup.md)
        - Example changes do not require unit or integration tests

        **Workflow / GitHub Actions changes (e.g. files in `.github/`):**
        - Where possible, test by merging to your fork's `main` and simulating the scenario (e.g. creating a test issue or PR)
        - Link to any test issues or PRs you created as evidence
        - See the [workflow testing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/11_submit_pull_request.md)
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Done Checklist
      description: |
        EDIT OR ADD CRITERIA SPECIFIC TO THIS ISSUE. THE DEFAULTS COVER THE STANDARD REQUIREMENTS.
      value: |
        Before opening your PR, confirm:

        - [ ] My changes address what the issue asked for — nothing more, nothing less
        - [ ] I tested my changes locally (if relevant — see testing section above)
        - [ ] My commits are signed: `git commit -S -s -m "chore: description"` — [Signing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md)
        - [ ] I added a CHANGELOG.md entry under `[Unreleased]` — [Changelog guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md)
        - [ ] All CI checks pass
    validations:
      required: true

  - type: textarea
    id: contribution_steps
    attributes:
      label: 📋 Workflow quick reference
      description: |
        PRE-FILLED REFERENCE TABLE. LEAVE AS-IS.
      value: |
        You have done this before — here are the links if you need them:

        | Step | Guide |
        |------|-------|
        | Claim this issue | Comment `/assign` below |
        | Sync with main | [Rebasing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/rebasing.md) |
        | Open a PR and link this issue | [PR guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/11_submit_pull_request.md) · [Linking guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/how_to_link_issues.md) |
        | Resolve merge conflicts | [Merge conflicts guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/merge_conflicts.md) |
    validations:
      required: false

  - type: textarea
    id: ai_tips
    attributes:
      label: 🤖 Tips for using AI tools
      description: |
        PRE-FILLED GUIDANCE. LEAVE AS-IS.
      value: |
        Here is how to get the most out of AI tools:

        - Use [Pylance](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/pylance.md) in VS Code to catch errors and hallucinated methods in real time
        - Build your solution in small steps — add print statements or logs to confirm each piece works before moving on
        - When AI suggests code, check it against existing examples and similar classes in the SDK — that is the best source of Python SDK-specific patterns. AI sometimes borrows from other SDKs.
        - If AI output and SDK patterns disagree, trust the SDK
    validations:
      required: false

  - type: textarea
    id: stuck
    attributes:
      label: 🆘 Stuck?
      description: |
        PRE-FILLED GUIDANCE. LEAVE AS-IS.
      value: |
        Beginner issues can be tricky — it is completely normal to get blocked. Here is what to do:

        - **Comment on this issue** and describe what you have tried. A maintainer will respond.
        - **Ask on [Discord](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md)** in #hiero-python-sdk for quick questions.
        - **Join [Office Hours](https://zoom-lfx.platform.linuxfoundation.org/meeting/99912667426?password=5b584a0e-1ed7-49d3-b2fc-dc5ddc888338)** (Wednesdays, 2pm UTC) for live, hands-on help with a maintainer — screen sharing welcome.

        Do not spend more than 30 minutes blocked without asking. Asking good questions is a skill too.
    validations:
      required: false

  - type: textarea
    id: resources
    attributes:
      label: 📚 Resources
      description: |
        ADD ANY TASK-SPECIFIC RESOURCES BELOW — RELEVANT PYTHON DOCS, STACK OVERFLOW ANSWERS, OR SPECIFIC FILES IN THE CODEBASE.
      value: |
        **Project references:**
        - [Project structure](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/setup/project_structure.md)
        - [CONTRIBUTING.md](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/CONTRIBUTING.md)
        - [Browse closed beginner PRs](https://github.com/hiero-ledger/hiero-sdk-python/pulls?q=is%3Apr+is%3Amerged+label%3Abeginner) — see how others did it

        **Python references:**
        - [Python official docs](https://docs.python.org/3/)
        - [Data model (dunder methods)](https://docs.python.org/3/reference/datamodel.html)
        - [Type hints](https://docs.python.org/3/library/typing.html)
    validations:
      required: false
