name: Beginner Issue Template
description: Create a beginner issue for contributors ready to work more independently
title: "[Beginner]: "
labels: ["beginner"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ---
        **For issue creators:** Beginner issues sit between Good First Issues and Intermediate issues.
        The contributor should need to read some code, look something up, or make a small decision —
        but not design a solution from scratch.

        If the task can be completed by copy-pasting instructions, it belongs in a Good First Issue.
        If it requires understanding multiple interacting systems, it belongs in Intermediate.

        For detailed guidance, see the
        [Beginner Issue Guidelines](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/maintainers/beginner_issues_guidelines.md).

        **All links in this template must be absolute URLs** (starting with `https://`).
        Relative links break when rendered in GitHub issues.

        ---

  - type: markdown
    attributes:
      value: |
        ### Before you start

        Beginner issues assume you have already completed a Good First Issue (or equivalent contribution).
        You should be able to:

        - Fork, branch, commit (with DCO + GPG signing), and open a pull request without a tutorial
        - Read Python code you did not write and follow its patterns
        - Look things up on your own before asking for help

        If any of that feels unfamiliar, start with a
        [Good First Issue](https://github.com/hiero-ledger/hiero-sdk-python/issues?q=is%3Aissue+state%3Aopen+label%3A%22Good+First+Issue%22+no%3Aassignee)
        instead. No shame in it — that is what they are for.

  - type: textarea
    id: task
    attributes:
      label: The Task
      description: |
        DESCRIBE WHAT NEEDS TO CHANGE AND WHY.
        INCLUDE WHICH FILE(S) TO LOOK AT, WHAT THE CURRENT BEHAVIOR IS, AND WHAT THE DESIRED BEHAVIOR IS.
        DO NOT WRITE A STEP-BY-STEP RECIPE. POINT THEM TOWARD THE RIGHT AREA AND LET THEM FIGURE OUT THE APPROACH.
        IF A COPY-PASTE RECIPE WOULD SUFFICE, THIS IS A GOOD FIRST ISSUE, NOT A BEGINNER ISSUE.
      value: |
        _Replace this with the task description._
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example task (hidden in submission) -->
        ## Example — The Task

        The `AccountId` class in `src/hiero_sdk_python/account/account_id.py` has a `__str__()` method,
        but its `__repr__()` still uses the default object representation:

        ```python
        >>> repr(account_id)
        '<hiero_sdk_python.account.account_id.AccountId object at 0x7f9c2a3b8d60>'
        ```

        That is not useful when debugging. We want `repr()` to show the actual values:

        ```python
        >>> repr(account_id)
        'AccountId(shard=0, realm=0, num=1234)'
        ```

        The class is initialized with `shard`, `realm`, `num`, and an optional `alias_key`.
        Look at how other ID classes in the SDK handle `__repr__()` for the expected pattern.

  - type: textarea
    id: exploration
    attributes:
      label: Where to Start
      description: |
        POINT THE CONTRIBUTOR TOWARD RELEVANT FILES, SIMILAR CODE, OR PATTERNS TO STUDY.
        DO NOT PROVIDE THE COMPLETE SOLUTION.
        THINK: WHAT WOULD A COLLEAGUE TELL YOU IF YOU ASKED "WHERE DO I START?"
        INCLUDE LINKS TO PYTHON DOCUMENTATION IF THE TASK INVOLVES A LANGUAGE CONCEPT.
      value: |
        _Replace this with exploration pointers._
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <!-- Example exploration pointers (hidden in submission) -->
        ## Example — Where to Start

        - Open `src/hiero_sdk_python/account/account_id.py` and read the `__init__` and `__str__` methods
        - Look at how `TopicId` and `ContractId` implement `__repr__()` — use the same pattern
        - Python docs on `__repr__`: https://docs.python.org/3/reference/datamodel.html#object.__repr__
        - Ask yourself: what information would help you identify this object during debugging?
        - Check the existing unit test file for `AccountId` and add a test for your new method

  - type: textarea
    id: acceptance
    attributes:
      label: Done Checklist
      description: |
        EDIT OR ADD CRITERIA SPECIFIC TO THIS ISSUE. THE DEFAULTS COVER THE STANDARD REQUIREMENTS.
      value: |
        Before opening your PR, confirm:

        - [ ] My changes address what the issue asked for — nothing more, nothing less
        - [ ] I tested my changes locally (ran relevant tests, checked output)
        - [ ] I did not modify files unrelated to this issue
        - [ ] My commits are signed: `git commit -S -s -m "chore: description"`
              [Signing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md)
        - [ ] I added a CHANGELOG.md entry under `[Unreleased]`
              [Changelog guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md)
        - [ ] All CI checks pass
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        > **Workflow quick reference** — you have done this before, here are the links if you need them
        >
        > | Step | Guide |
        > |------|-------|
        > | Claim this issue | Comment `/assign` below |
        > | Sync with main | [Rebasing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/rebasing.md) |
        > | Sign commits | [Signing guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/signing.md) |
        > | Add changelog entry | [Changelog guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/changelog_entry.md) |
        > | Open a PR and link this issue | [PR guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/workflow/11_submit_pull_request.md) · [Linking guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/how_to_link_issues.md) |
        > | Resolve merge conflicts | [Merge conflicts guide](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/merge_conflicts.md) |

  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > **Common mistakes on beginner issues**
        >
        > - **Changing files you were not asked to change.** Stick to the scope described above.
        > - **Forgetting to sign commits.** Every commit needs `-S -s`. Check with `git log --show-signature`.
        > - **Skipping the changelog.** Your PR will not merge without one.
        > - **Trusting AI output without reading it.** AI tools can help you explore and understand code,
        >   but they hallucinate methods, invent parameters, and change return types.
        >   Read every line before you commit it. Maintainers can tell.
        > - **Going silent when stuck.** If you have been blocked for more than 30 minutes, ask.
        >   Comment here, tag a maintainer, or ask on Discord. Struggling alone is not a skill.

  - type: textarea
    id: resources
    attributes:
      label: Resources
      description: |
        ADD ANY TASK-SPECIFIC RESOURCES BELOW — RELEVANT PYTHON DOCS, STACK OVERFLOW ANSWERS, OR SPECIFIC FILES IN THE CODEBASE.
      value: |
        **Stuck? Ask here:**
        - Comment on this issue and tag a maintainer
        - [Discord](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/discord.md) — fastest for quick questions
        - [Office Hours](https://zoom-lfx.platform.linuxfoundation.org/meeting/99912667426?password=5b584a0e-1ed7-49d3-b2fc-dc5ddc888338) — Wednesdays, 2pm UTC, live help

        **Project references:**
        - [Project structure](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/docs/sdk_developers/training/setup/project_structure.md)
        - [CONTRIBUTING.md](https://github.com/hiero-ledger/hiero-sdk-python/blob/main/CONTRIBUTING.md)
        - [Browse closed beginner PRs](https://github.com/hiero-ledger/hiero-sdk-python/pulls?q=is%3Apr+is%3Amerged+label%3Abeginner) — see how others did it

        **Python references:**
        - [Python official docs](https://docs.python.org/3/)
        - [Data model (dunder methods)](https://docs.python.org/3/reference/datamodel.html)
        - [Type hints](https://docs.python.org/3/library/typing.html)
    validations:
      required: false
