# Auto-generated proto imports per token module

# abstract_token_transfer_transaction.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# custom_fixed_fee.py
import hiero_sdk_python.hapi.services.custom_fees_pb2

# hbar_allowance.py
import hiero_sdk_python.hapi.services.crypto_approve_allowance_pb2.CryptoAllowance

# hbar_transfer.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# nft_id.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_airdrop_claim.py
import hiero_sdk_python.hapi.services.token_claim_airdrop_pb2.TokenClaimAirdropTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2

# token_airdrop_pending_id.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_airdrop_pending_record.py
import hiero_sdk_python.hapi.services.basic_types_pb2
import hiero_sdk_python.hapi.services.transaction_record_pb2

# token_airdrop_transaction.py
import hiero_sdk_python.hapi.services.token_airdrop_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_airdrop_transaction_cancel.py
import hiero_sdk_python.hapi.services.basic_types_pb2
import hiero_sdk_python.hapi.services.token_cancel_airdrop_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_allowance.py
import hiero_sdk_python.hapi.services.crypto_approve_allowance_pb2.TokenAllowance

# token_associate_transaction.py
import hiero_sdk_python.hapi.services.token_associate_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_burn_transaction.py
import hiero_sdk_python.hapi.services.token_burn_pb2.TokenBurnTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.token_burn_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_create_transaction.py
import hiero_sdk_python.hapi.services.token_create_pb2
import hiero_sdk_python.hapi.services.basic_types_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_delete_transaction.py
import hiero_sdk_python.hapi.services.token_delete_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_dissociate_transaction.py
import hiero_sdk_python.hapi.services.token_dissociate_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_fee_schedule_update_transaction.py
import hiero_sdk_python.hapi.services.token_fee_schedule_update_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_freeze_status.py
import hiero_sdk_python.hapi.services.basic_types_pb2.TokenFreezeStatus

# token_freeze_transaction.py
import hiero_sdk_python.hapi.services.token_freeze_account_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_grant_kyc_transaction.py
import hiero_sdk_python.hapi.services.token_grant_kyc_pb2.TokenGrantKycTransactionBody
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody
import hiero_sdk_python.hapi.services.token_grant_kyc_pb2
import hiero_sdk_python.hapi.services.transaction_pb2

# token_id.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_info.py
import hiero_sdk_python.hapi.services.token_get_info_pb2

# token_key_validation.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_kyc_status.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_mint_transaction.py
import hiero_sdk_python.hapi.services.token_mint_pb2.TokenMintTransactionBody
import hiero_sdk_python.hapi.services.token_mint_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_nft_allowance.py
import hiero_sdk_python.hapi.services.crypto_approve_allowance_pb2.NftAllowance
import hiero_sdk_python.hapi.services.crypto_delete_allowance_pb2.NftRemoveAllowance

# token_nft_info.py
import hiero_sdk_python.hapi.services.timestamp_pb2
import hiero_sdk_python.hapi.services.token_get_nft_info_pb2

# token_nft_transfer.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_pause_status.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_pause_transaction.py
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.token_pause_pb2
import hiero_sdk_python.hapi.services.token_pause_pb2.TokenPauseTransactionBody
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_reject_transaction.py
import hiero_sdk_python.hapi.services.token_reject_pb2.TokenReference
import hiero_sdk_python.hapi.services.token_reject_pb2.TokenRejectTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_relationship.py
import hiero_sdk_python.hapi.services.basic_types_pb2.TokenRelationship
import hiero_sdk_python.hapi.services.basic_types_pb2.TokenFreezeStatus
import hiero_sdk_python.hapi.services.basic_types_pb2.TokenKycStatus

# token_revoke_kyc_transaction.py
import hiero_sdk_python.hapi.services.token_revoke_kyc_pb2.TokenRevokeKycTransactionBody
import hiero_sdk_python.hapi.services.token_revoke_kyc_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_transfer.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_transfer_list.py
import hiero_sdk_python.hapi.services.basic_types_pb2

# token_unfreeze_transaction.py
import hiero_sdk_python.hapi.services.token_unfreeze_account_pb2
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

# token_unpause_transaction.py
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody
import hiero_sdk_python.hapi.services.token_unpause_pb2.TokenUnpauseTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2.TransactionBody

# token_update_nfts_transaction.py
import hiero_sdk_python.hapi.services.token_update_nfts_pb2.TokenUpdateNftsTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody
import hiero_sdk_python.hapi.services.token_update_nfts_pb2

# token_update_transaction.py
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody
import hiero_sdk_python.hapi.services.token_update_pb2
import hiero_sdk_python.hapi.services.transaction_pb2

# token_wipe_transaction.py
import hiero_sdk_python.hapi.services.token_wipe_account_pb2
import hiero_sdk_python.hapi.services.token_wipe_account_pb2.TokenWipeAccountTransactionBody
import hiero_sdk_python.hapi.services.transaction_pb2
import hiero_sdk_python.hapi.services.schedulable_transaction_body_pb2.SchedulableTransactionBody

