# Auto-generated proto attributes and setters

proto_mappings = {
    'CryptoAllowance': {
        'attributes': [
            'owner',
            'spender',
            'amount',
        ],
        'setters': [
            'set_owner',
            'set_spender',
            'set_amount',
        ]
    },
    'NftAllowance': {
        'attributes': [
            'tokenId',
            'owner',
            'spender',
            'serial_numbers',
            'approved_for_all',
            'delegating_spender',
        ],
        'setters': [
            'set_tokenId',
            'set_owner',
            'set_spender',
            'set_serial_numbers',
            'set_approved_for_all',
            'set_delegating_spender',
        ]
    },
    'NftRemoveAllowance': {
        'attributes': [
            'token_id',
            'owner',
            'serial_numbers',
        ],
        'setters': [
            'set_token_id',
            'set_owner',
            'set_serial_numbers',
        ]
    },
    'SchedulableTransactionBody': {
        'attributes': [
            'transactionFee',
            'memo',
            'contractCall',
            'contractCreateInstance',
            'contractUpdateInstance',
            'contractDeleteInstance',
            'cryptoCreateAccount',
            'cryptoDelete',
            'cryptoTransfer',
            'cryptoUpdateAccount',
            'fileAppend',
            'fileCreate',
            'fileDelete',
            'fileUpdate',
            'systemDelete',
            'systemUndelete',
            'freeze',
            'consensusCreateTopic',
            'consensusUpdateTopic',
            'consensusDeleteTopic',
            'consensusSubmitMessage',
            'tokenCreation',
            'tokenFreeze',
            'tokenUnfreeze',
            'tokenGrantKyc',
            'tokenRevokeKyc',
            'tokenDeletion',
            'tokenUpdate',
            'tokenMint',
            'tokenBurn',
            'tokenWipe',
            'tokenAssociate',
            'tokenDissociate',
            'scheduleDelete',
            'token_pause',
            'token_unpause',
            'cryptoApproveAllowance',
            'cryptoDeleteAllowance',
            'token_fee_schedule_update',
            'util_prng',
            'token_update_nfts',
            'nodeCreate',
            'nodeUpdate',
            'nodeDelete',
            'tokenReject',
            'tokenCancelAirdrop',
            'tokenClaimAirdrop',
            'tokenAirdrop',
            'max_custom_fees',
        ],
        'setters': [
            'set_transactionFee',
            'set_memo',
            'set_contractCall',
            'set_contractCreateInstance',
            'set_contractUpdateInstance',
            'set_contractDeleteInstance',
            'set_cryptoCreateAccount',
            'set_cryptoDelete',
            'set_cryptoTransfer',
            'set_cryptoUpdateAccount',
            'set_fileAppend',
            'set_fileCreate',
            'set_fileDelete',
            'set_fileUpdate',
            'set_systemDelete',
            'set_systemUndelete',
            'set_freeze',
            'set_consensusCreateTopic',
            'set_consensusUpdateTopic',
            'set_consensusDeleteTopic',
            'set_consensusSubmitMessage',
            'set_tokenCreation',
            'set_tokenFreeze',
            'set_tokenUnfreeze',
            'set_tokenGrantKyc',
            'set_tokenRevokeKyc',
            'set_tokenDeletion',
            'set_tokenUpdate',
            'set_tokenMint',
            'set_tokenBurn',
            'set_tokenWipe',
            'set_tokenAssociate',
            'set_tokenDissociate',
            'set_scheduleDelete',
            'set_token_pause',
            'set_token_unpause',
            'set_cryptoApproveAllowance',
            'set_cryptoDeleteAllowance',
            'set_token_fee_schedule_update',
            'set_util_prng',
            'set_token_update_nfts',
            'set_nodeCreate',
            'set_nodeUpdate',
            'set_nodeDelete',
            'set_tokenReject',
            'set_tokenCancelAirdrop',
            'set_tokenClaimAirdrop',
            'set_tokenAirdrop',
            'set_max_custom_fees',
        ]
    },
    'TokenAllowance': {
        'attributes': [
            'tokenId',
            'owner',
            'spender',
            'amount',
        ],
        'setters': [
            'set_tokenId',
            'set_owner',
            'set_spender',
            'set_amount',
        ]
    },
    'TokenBurnTransactionBody': {
        'attributes': [
            'token',
            'amount',
            'serialNumbers',
        ],
        'setters': [
            'set_token',
            'set_amount',
            'set_serialNumbers',
        ]
    },
    'TokenClaimAirdropTransactionBody': {
        'attributes': [
            'pending_airdrops',
        ],
        'setters': [
            'set_pending_airdrops',
        ]
    },
    'TokenFreezeStatus': {
        'attributes': [
        ],
        'setters': [
        ]
    },
    'TokenGrantKycTransactionBody': {
        'attributes': [
            'token',
            'account',
        ],
        'setters': [
            'set_token',
            'set_account',
        ]
    },
    'TokenKycStatus': {
        'attributes': [
        ],
        'setters': [
        ]
    },
    'TokenMintTransactionBody': {
        'attributes': [
            'token',
            'amount',
            'metadata',
        ],
        'setters': [
            'set_token',
            'set_amount',
            'set_metadata',
        ]
    },
    'TokenPauseTransactionBody': {
        'attributes': [
            'token',
        ],
        'setters': [
            'set_token',
        ]
    },
    'TokenReference': {
        'attributes': [
            'fungible_token',
            'nft',
        ],
        'setters': [
            'set_fungible_token',
            'set_nft',
        ]
    },
    'TokenRejectTransactionBody': {
        'attributes': [
            'owner',
            'rejections',
        ],
        'setters': [
            'set_owner',
            'set_rejections',
        ]
    },
    'TokenRelationship': {
        'attributes': [
            'tokenId',
            'symbol',
            'balance',
            'kycStatus',
            'freezeStatus',
            'decimals',
            'automatic_association',
        ],
        'setters': [
            'set_tokenId',
            'set_symbol',
            'set_balance',
            'set_kycStatus',
            'set_freezeStatus',
            'set_decimals',
            'set_automatic_association',
        ]
    },
    'TokenRevokeKycTransactionBody': {
        'attributes': [
            'token',
            'account',
        ],
        'setters': [
            'set_token',
            'set_account',
        ]
    },
    'TokenUnpauseTransactionBody': {
        'attributes': [
            'token',
        ],
        'setters': [
            'set_token',
        ]
    },
    'TokenUpdateNftsTransactionBody': {
        'attributes': [
            'token',
            'serial_numbers',
            'metadata',
        ],
        'setters': [
            'set_token',
            'set_serial_numbers',
            'set_metadata',
        ]
    },
    'TokenWipeAccountTransactionBody': {
        'attributes': [
            'token',
            'account',
            'amount',
            'serialNumbers',
        ],
        'setters': [
            'set_token',
            'set_account',
            'set_amount',
            'set_serialNumbers',
        ]
    },
    'TransactionBody': {
        'attributes': [
            'transactionID',
            'nodeAccountID',
            'transactionFee',
            'transactionValidDuration',
            'generateRecord',
            'memo',
            'batch_key',
            'contractCall',
            'contractCreateInstance',
            'contractUpdateInstance',
            'cryptoAddLiveHash',
            'cryptoCreateAccount',
            'cryptoDelete',
            'cryptoDeleteLiveHash',
            'cryptoTransfer',
            'cryptoUpdateAccount',
            'fileAppend',
            'fileCreate',
            'fileDelete',
            'fileUpdate',
            'systemDelete',
            'systemUndelete',
            'contractDeleteInstance',
            'freeze',
            'consensusCreateTopic',
            'consensusUpdateTopic',
            'consensusDeleteTopic',
            'consensusSubmitMessage',
            'uncheckedSubmit',
            'tokenCreation',
            'tokenFreeze',
            'tokenUnfreeze',
            'tokenGrantKyc',
            'tokenRevokeKyc',
            'tokenDeletion',
            'tokenUpdate',
            'tokenMint',
            'tokenBurn',
            'tokenWipe',
            'tokenAssociate',
            'tokenDissociate',
            'scheduleCreate',
            'scheduleDelete',
            'scheduleSign',
            'token_fee_schedule_update',
            'token_pause',
            'token_unpause',
            'cryptoApproveAllowance',
            'cryptoDeleteAllowance',
            'ethereumTransaction',
            'node_stake_update',
            'util_prng',
            'token_update_nfts',
            'nodeCreate',
            'nodeUpdate',
            'nodeDelete',
            'tokenReject',
            'tokenAirdrop',
            'tokenCancelAirdrop',
            'tokenClaimAirdrop',
            'state_signature_transaction',
            'hints_preprocessing_vote',
            'hints_key_publication',
            'hints_partial_signature',
            'history_proof_signature',
            'history_proof_key_publication',
            'history_proof_vote',
            'crs_publication',
            'atomic_batch',
            'lambda_sstore',
            'hook_dispatch',
            'max_custom_fees',
        ],
        'setters': [
            'set_transactionID',
            'set_nodeAccountID',
            'set_transactionFee',
            'set_transactionValidDuration',
            'set_generateRecord',
            'set_memo',
            'set_batch_key',
            'set_contractCall',
            'set_contractCreateInstance',
            'set_contractUpdateInstance',
            'set_cryptoAddLiveHash',
            'set_cryptoCreateAccount',
            'set_cryptoDelete',
            'set_cryptoDeleteLiveHash',
            'set_cryptoTransfer',
            'set_cryptoUpdateAccount',
            'set_fileAppend',
            'set_fileCreate',
            'set_fileDelete',
            'set_fileUpdate',
            'set_systemDelete',
            'set_systemUndelete',
            'set_contractDeleteInstance',
            'set_freeze',
            'set_consensusCreateTopic',
            'set_consensusUpdateTopic',
            'set_consensusDeleteTopic',
            'set_consensusSubmitMessage',
            'set_uncheckedSubmit',
            'set_tokenCreation',
            'set_tokenFreeze',
            'set_tokenUnfreeze',
            'set_tokenGrantKyc',
            'set_tokenRevokeKyc',
            'set_tokenDeletion',
            'set_tokenUpdate',
            'set_tokenMint',
            'set_tokenBurn',
            'set_tokenWipe',
            'set_tokenAssociate',
            'set_tokenDissociate',
            'set_scheduleCreate',
            'set_scheduleDelete',
            'set_scheduleSign',
            'set_token_fee_schedule_update',
            'set_token_pause',
            'set_token_unpause',
            'set_cryptoApproveAllowance',
            'set_cryptoDeleteAllowance',
            'set_ethereumTransaction',
            'set_node_stake_update',
            'set_util_prng',
            'set_token_update_nfts',
            'set_nodeCreate',
            'set_nodeUpdate',
            'set_nodeDelete',
            'set_tokenReject',
            'set_tokenAirdrop',
            'set_tokenCancelAirdrop',
            'set_tokenClaimAirdrop',
            'set_state_signature_transaction',
            'set_hints_preprocessing_vote',
            'set_hints_key_publication',
            'set_hints_partial_signature',
            'set_history_proof_signature',
            'set_history_proof_key_publication',
            'set_history_proof_vote',
            'set_crs_publication',
            'set_atomic_batch',
            'set_lambda_sstore',
            'set_hook_dispatch',
            'set_max_custom_fees',
        ]
    },
}
