name: PythonBot - Assignment Limit

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  check-assignment-limit:
    runs-on: hl-sdk-py-lin-md
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check Assignment Count
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSIGNEE: ${{ github.event.assignee.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          MENTOR_LABEL: "notes: mentor-duty"
        run: |
          # Make script executable (just in case permissions were lost during checkout)
          chmod +x .github/scripts/bot-assignment-check.sh

          # Run the script
          ./.github/scripts/bot-assignment-check.sh
