name: Mypy Type Check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  mypy-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mypy

      - name: Run mypy
        run: mypy src/hiero_sdk_python
        continue-on-error: true
